### PR TITLE
Update multiple delete

### PR DESCRIPTION
**Pull request by LIUJIAHAOCS**

### CODE REVIEW

**Comment by LIUJIAHAOCS** [comment]
need to add regex to check user input format before perform deletion(Done)

**Comment by LIUJIAHAOCS** [comment]
Some test cases cannot pass due to this change-gui-branch. feature branch related test cases have been added.

**Comment by deltango** [comment]
Good PR, multiple delete function will be helpful.

**Review by deltango — APPROVED** [review]

**Review by yong24s — COMMENTED** [review]
Good use of SLAP.

Junit seems to cover all cases.

May want to refractor date parser to a utility class for other UI to use

**Pull request merged**
